language: swift
osx_image: xcode9.3beta
xcode_workspace: Tank.xcworkspace
xcode_scheme: TankAndTests
before_install:
  - pod repo update
script:
  - xcodebuild -workspace Tank.xcworkspace -scheme TankAndTests build-for-testing -quiet
  - xctool -workspace Tank.xcworkspace -scheme TankAndTests run-tests
