language: swift
osx_image: xcode9.2

env:
  - APP_PATH=""
before_install:
  - pod repo update
script:
  - xcodebuild -workspace Tank.xcworkspace -scheme TankAndTests -enableCodeCoverage YES build test
  - xcodebuild -workspace Tank.xcworkspace -scheme TankRelease build
notifications:
  slack:
    rooms:
      - ailurusworkspace:Gjchyw98WhkfwHdNgMBG1vEl#tank
    on_success: never
    on_failure: change
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - git config --local user.name "Xavier Bauquet"
  - git config --local user.email "xavier.bauquet@gmail.com"
  - cp -r /Users/travis/Library/Developer/Xcode/DerivedData/Tank-*/Build/Products/Release/Tank.app .
  - zip -r Tank.zip Tank.app
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "Tank.zip"
  skip_cleanup: true
  on:
    tags: true
