language: swift
osx_image: xcode9.2
xcode_workspace: Tank.xcworkspace
xcode_scheme: TankAndTests
before_install:
  - pod repo update
script:
  - xcodebuild -workspace Tank.xcworkspace -scheme TankAndTests -quiet -enableCodeCoverage YES build test
notifications:
  slack:
    rooms:
      - ailurusworkspace:Gjchyw98WhkfwHdNgMBG1vEl#tank
    on_success: never
    on_failure: change
after_success:
  - bash <(curl -s https://codecov.io/bash)
